M48
; DRILL file {KiCad 9.0.6} date 2025-12-16T17:11:08+0700
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2025-12-16T17:11:08+07:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.6
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0591
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.0709
%
G90
G05
T1
X1.0266Y0.2177
X1.2175Y0.2177
T2
X1.0148Y0.0984
X1.2293Y0.0984
M30
