M48
; DRILL file {KiCad 9.0.4} date 2025-10-07T14:59:12+0700
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2025-10-07T14:59:12+07:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.4
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.1260
%
G90
G05
T1
X0.1378Y2.2047
X0.1378Y-0.0492
X1.3287Y2.2047
X1.3287Y-0.0492
M30
