M48
; DRILL file {KiCad 8.0.6} date 2024-10-28T10:58:13+0700
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2024-10-28T10:58:13+07:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,8.0.6
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C1.500
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C1.800
%
G90
G05
T1
X26.075Y5.53
X30.925Y5.53
T2
X25.775Y2.5
X31.225Y2.5
M30
