//!
//! \file       dac.c
//! \author     Abdelrahman Ali (split from max14866.c by Claude, 2026-09-12)
//! \brief      MCP4812 gain DAC driver (always built; independent of -DMUX).
//!

//---------------------------------------------------------------------------
// INCLUDES
//---------------------------------------------------------------------------

#include "dac.h"

// The DAC reuses the generic SPI-shifter PIO program declared in max14866.pio.
// That header is always generated by CMake, even when the MUX is excluded.
#include "max14866.pio.h"

//---------------------------------------------------------------------------
// FILE-LOCAL STATE
//---------------------------------------------------------------------------

static PIO pio_dac;
static uint sm_dac;
static uint16_t dac_reg;

//---------------------------------------------------------------------------
// DAC INIT FUNCTION
//---------------------------------------------------------------------------
void dac_init()
{
    pio_dac = pio1;
    sm_dac = 1;
    uint offset = pio_add_program(pio_dac, &max14866_program);
    max14866_program_init(pio_dac, sm_dac, offset, DAC_MOSI, DAC_SCLK, DAC_CLK);
    gpio_init(DAC_CS);
    gpio_set_dir(DAC_CS, GPIO_OUT);
    gpio_put(DAC_CS, 1);
}

//---------------------------------------------------------------------------
// DAC DATA CALCULATION
//---------------------------------------------------------------------------
void dac_data_calculation(uint16_t *data, uint16_t input, uint16_t config_bits)
{
    *data = 0;
    *data = (uint16_t)(input);
    *data = ((*data << 2) | config_bits);
}

//---------------------------------------------------------------------------
// DAC WRITE FUNCTION
//---------------------------------------------------------------------------
void dac_write(uint16_t data)
{
    max14866_wait_idle(pio_dac, sm_dac);
    gpio_put(DAC_CS, 0);
    max14866_put(pio_dac, sm_dac, data);
    max14866_wait_idle(pio_dac, sm_dac);
    gpio_put(DAC_CS, 1);
}

//---------------------------------------------------------------------------
// DAC MAIN FUNCTION
//---------------------------------------------------------------------------
void dac(const char *input)
{
    printf("DAC writing started\n");
    dac_data_calculation(&dac_reg, atoi(input), 0x3000);
    dac_write(dac_reg);
    printf("DAC writing ended\n");
}

//---------------------------------------------------------------------------
// END OF FILE
//---------------------------------------------------------------------------
