M48
; DRILL file KiCad 10.0.4-10.0.4~ubuntu22.04.1 date 2026-09-12T00:10:08
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-09-12T00:10:08+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,10.0.4-10.0.4~ubuntu22.04.1
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C1.500
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C1.800
%
G90
G05
T1
X146.325Y-117.97
X151.175Y-117.97
T2
X146.025Y-121.0
X151.475Y-121.0
M30
